name: 'GitHub Project Automation+'
description: '🤖 Automate GitHub Project cards with any webhook event'
author: 'Alex Page <alex@alexpage.com.au>'
inputs:
  repo-token:
    description: 'The GH_TOKEN secret can be passed in using {{ secrets.GH_TOKEN }}'
    required: true
  project:
    description: 'The name of the GitHub Project'
    required: true
  column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
  column-allow-list:
    type: string
    description: 'Columns which cards are allowed to be moved from. If not specified, all columns are allowed. Multiple columns separated by newline or comma.'
    required: false
    default: ''
  column-deny-list:
    type: string
    description: 'Columns which cards are not allowed to be moved from. If not specified, no columns are denied. Multiple columns separated by newline or comma.'
    required: false
    default: ''
  action:
    description: |
      Can be `update`, `delete` or `archive` or `add`. This determines the type of the action
      to be performed on the card
    required: false
    default: "update"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'gray-dark'
